apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dozzle
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/skncvo/infra.git
    targetRevision: HEAD
    path: devops-platform/platform/dozzle
  destination:
    server: https://kubernetes.default.svc
    namespace: dozzle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
