apiVersion: v2
name: harbor-wrapper
description: Harbor wrapper chart for ArgoCD
type: application
version: 0.1.0

dependencies:
  - name: harbor
    version: 1.14.0
    repository: https://helm.goharbor.io
