- name: Install local-path provisioner
  shell: kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
  register: local_path_apply
  changed_when: "'created' in local_path_apply.stdout or 'configured' in local_path_apply.stdout"

- name: Set local-path as default storageclass
  shell: >
    kubectl patch storageclass local-path
    -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  register: local_path_default
  changed_when: "'patched' in local_path_default.stdout or 'configured' in local_path_default.stdout"

- name: Show storageclasses
  command: kubectl get storageclass
  register: storageclass_result
  changed_when: false

- name: Print storageclasses
  debug:
    var: storageclass_result.stdout_lines
